In [2]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Fashion_Retail_Sales_Cleaned_Final.csv')

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Channel', 'Payment_Method',
       'Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Age_Group',
       'Customer_Type', 'Segment', 'Product_Category', 'Product_Name', 'Brand',
       'Size', 'Color', 'Units_Sold', 'Unit_Price', 'Discount_%',
       'Sales_Amount', 'Cost_Amount', 'City', 'State', 'Region',
       'Return_Status', 'Order_Year', 'Order_Quarter', 'Profit',
       'Profit_Margin_%', 'Order_Month'],
      dtype='object')

In [9]:
df[['Sales_Amount','Profit']].describe()

       Sales_Amount        Profit
count   4000.000000   4000.000000
mean    3057.604650    862.224590
std     5651.733293   2108.623765
min      194.350000 -31226.790000
25%      998.000000    228.105000
50%     1522.900000    457.595000
75%     2598.000000    857.385000
max    64936.800000  21498.120000

In [19]:
q1_sales = 998
q3_sales = 1522.9
q1_profit = 228.105000
q3_profit = 857.385000

In [21]:
df['Sales_Category'] = df['Sales_Amount'].apply(
    lambda x : 'Low Sales' if x <= q1_sales
    else 'Medium Sales' if q1_sales < x <= q3_sales
    else 'High Sales'
                                            )

In [23]:
df[['Sales_Amount','Sales_Category']]

      Sales_Amount Sales_Category
0          1099.00   Medium Sales
1          1039.35   Medium Sales
2          1257.20   Medium Sales
3          1279.65   Medium Sales
4          1918.40     High Sales
...            ...            ...
3995       2097.00     High Sales
3996        299.40      Low Sales
3997        239.20      Low Sales
3998       1049.30   Medium Sales
3999       2239.20     High Sales

[4000 rows x 2 columns]

In [25]:
def categorize_profit(x):
    if x < 0:
        return 'Loss'
    elif x == 0:
        return 'Break-Even'
    elif x < q3_profit:
        return 'Low Profit'
    else:
        return 'High Profit'

df['Profit_Category'] = df['Profit'].apply(categorize_profit)

In [27]:
df[['Profit' , 'Profit_Category']]

      Profit Profit_Category
0     503.92      Low Profit
1     179.64      Low Profit
2     327.08      Low Profit
3     676.47      Low Profit
4     722.90      Low Profit
...      ...             ...
3995  868.50     High Profit
3996   29.28      Low Profit
3997   81.40      Low Profit
3998  209.83      Low Profit
3999  486.50      Low Profit

[4000 rows x 2 columns]

In [47]:
Customer_Order_Count = df.groupby('Customer_ID')['Order_ID'].nunique()
df['Customer_Order_Count'] = df['Customer_ID'].map(Customer_Order_Count)
df['Customer_Order_Count']

0        2
1        1
2       13
3        1
4        3
        ..
3995     3
3996     9
3997     4
3998     5
3999     4
Name: Customer_Order_Count, Length: 4000, dtype: int64

In [49]:
df['Customer_Type'] = df['Customer_Order_Count'].apply(
    lambda x: 'One-Time Customer' if x == 1
    else 'Occasional Customer' if 2 <= x <= 6
    else 'Frequent Customer'
)

In [51]:
df[['Customer_Order_Count', 'Customer_Type']]

      Customer_Order_Count        Customer_Type
0                        2  Occasional Customer
1                        1    One-Time Customer
2                       13    Frequent Customer
3                        1    One-Time Customer
4                        3  Occasional Customer
...                    ...                  ...
3995                     3  Occasional Customer
3996                     9    Frequent Customer
3997                     4  Occasional Customer
3998                     5  Occasional Customer
3999                     4  Occasional Customer

[4000 rows x 2 columns]

In [59]:
Product_Sales = df.groupby('Product_Name')['Sales_Amount'].sum()
Product_Sales

Product_Name
A-Line Dress              113868.70
Backpack                  407521.50
Baggy Jeans               288952.45
Ballet Flats               38288.40
Basic Crew Neck Tee       213091.85
Block Heels                40325.05
Bomber Jacket             424913.20
Cap                       187988.50
Cargo Trousers            381934.25
Casual Dress              167725.20
Casual Shirt              443472.20
Casual Sneakers           569750.35
Chinos                    311279.15
Crewneck Sweatshirt       272203.75
Crop T-Shirt              112716.85
Denim Jacket              301898.45
Flannel Shirt             142371.60
Floral Midi Dress         181176.90
Formal Shirt              187447.40
Formal Shoes              125707.90
Formal Trousers           114055.25
Graphic Tee               291821.40
Henley T-Shirt            150168.80
High-Rise Skinny Jeans    141243.40
Hoodie                    484638.75
Jogger Pants              380778.90
Leather Belt               77390.60
Leather Biker Jacket       86252.20
Linen Shirt               462873.70
Loafers                   148789.40
Maxi Dress                158164.10
Mom Fit Jeans             170011.85
Oversized Sweatshirt      249832.45
Oversized T-Shirt         459888.35
Oxford Shirt              177900.90
Palazzo Pants              95396.60
Party Wear Dress          162003.00
Polo T-Shirt              472107.95
Printed Resort Shirt      149800.85
Puffer Jacket             294113.75
Running Shoes             483579.75
Sandals                   181701.75
Scarf                      27855.20
Slim Fit Jeans            297952.05
Sling Bag                 256915.10
Socks Pack                142822.25
Straight Fit Jeans        355359.85
Sunglasses                151212.55
Tote Bag                  123406.65
Wallet                     59237.55
Windcheater               146249.30
Zip-up Hoodie             364260.75
Name: Sales_Amount, dtype: float64

In [55]:
Product_Sales.describe()

count        52.000000
mean     235200.357692
std      139063.811044
min       27855.200000
25%      142089.550000
50%      181439.325000
75%      322299.325000
max      569750.350000
Name: Sales_Amount, dtype: float64

In [57]:
q1_product_sales = 142089.550
q3_product_sales = 322299.325

In [63]:
Product_Performance = Product_Sales.apply(
    lambda x: 'Low Performer' if x <= q1_product_sales
    else 'Average Performer' if x <= q3_product_sales
    else 'High Performer'
)

In [65]:
df['Product_Performance'] = df['Product_Name'].map(Product_Performance)

In [84]:
df[['Product_Name','Product_Performance' ]].sort_values(by = 'Product_Performance')

           Product_Name Product_Performance
3999       Denim Jacket   Average Performer
1595  Floral Midi Dress   Average Performer
3102        Windcheater   Average Performer
3103      Puffer Jacket   Average Performer
3105        Windcheater   Average Performer
...                 ...                 ...
2789       Leather Belt       Low Performer
3646       Leather Belt       Low Performer
1176        Block Heels       Low Performer
2765       Ballet Flats       Low Performer
3268           Tote Bag       Low Performer

[4000 rows x 2 columns]

In [88]:
Order_Units = df.groupby('Order_ID')['Units_Sold'].sum()

In [90]:
df['Total_Units_Per_Order'] = df['Order_ID'].map(Order_Units)

In [92]:
df[['Order_ID','Total_Units_Per_Order']]

            Order_ID  Total_Units_Per_Order
0     ORD-2025-00001                    1.0
1     ORD-2025-00002                    1.0
2     ORD-2025-00003                    4.0
3     ORD-2025-00004                    3.0
4     ORD-2025-00005                    2.0
...              ...                    ...
3995  ORD-2025-03996                    3.0
3996  ORD-2025-03997                    1.0
3997  ORD-2025-03998                    1.0
3998  ORD-2025-03999                    1.0
3999  ORD-2025-04000                    1.0

[4000 rows x 2 columns]

In [94]:
df['Total_Units_Per_Order'].describe()

count    4000.000000
mean        2.863250
std         4.976318
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        30.000000
Name: Total_Units_Per_Order, dtype: float64

In [96]:
df['Order_Size'] = df['Total_Units_Per_Order'].apply(
    lambda x: 'Small Order' if x <= 2
    else 'Medium Order' if x <= 5
    else 'Large Order'
)

In [98]:
df[['Total_Units_Per_Order', 'Order_Size']]

      Total_Units_Per_Order    Order_Size
0                       1.0   Small Order
1                       1.0   Small Order
2                       4.0  Medium Order
3                       3.0  Medium Order
4                       2.0   Small Order
...                     ...           ...
3995                    3.0  Medium Order
3996                    1.0   Small Order
3997                    1.0   Small Order
3998                    1.0   Small Order
3999                    1.0   Small Order

[4000 rows x 2 columns]

In [100]:
df.shape

(4000, 36)

In [105]:
df.to_csv('Fashion_Retail_Sales_Cleaned_Transformed.csv', index = False)

In [107]:
pf = pd.read_csv('Fashion_Retail_Sales_Cleaned_Transformed.csv')

In [109]:
pf.shape

(4000, 36)