In [75]:
import pandas as pd
import numpy as np

In [77]:
df = pd.read_csv('Fashion_Retail_Sales_Cleaned_Transformed.csv')

In [79]:
df.shape

(4000, 38)

In [24]:
Total_Revenue = df['Sales_Amount'].sum()
Total_Revenue

12230418.600000001

In [28]:
Total_Profit = df['Profit'].sum()
Total_Profit

3448898.36

In [32]:
Total_Orders = df['Order_ID'].count()
Total_Orders

4000

In [36]:
Total_Customers = df['Customer_ID'].nunique()
Total_Customers

1350

In [40]:
Average_Order_Value = Total_Revenue / Total_Orders
Average_Order_Value

3057.60465

In [44]:
Profit_Margin = (Total_Profit / Total_Revenue )*100
Profit_Margin

28.199348467108067

In [91]:
df['Previous_Month_Sales'] = df['Previous_Month_Sales'].fillna(0)
df['Previous_Month_Sales']

0             0.00
1             0.00
2             0.00
3             0.00
4             0.00
           ...
3995    1441314.65
3996    1441314.65
3997    1441314.65
3998    1441314.65
3999    1441314.65
Name: Previous_Month_Sales, Length: 4000, dtype: float64

In [93]:
monthly_summary = df.groupby('Year_Month')['Sales_Amount'].sum().reset_index()

monthly_summary['Previous_Month_Sales'] = (
    monthly_summary['Sales_Amount'].shift(1)
)

df['Previous_Month_Sales'] = df['Previous_Month_Sales'].fillna(0)
df['Previous_Month_Sales']

monthly_summary

   Year_Month  Sales_Amount  Previous_Month_Sales
0     2025-01     869432.00                   NaN
1     2025-02     826025.00             869432.00
2     2025-03    1033394.55             826025.00
3     2025-04     802252.60            1033394.55
4     2025-05     678614.90             802252.60
5     2025-06    1001841.95             678614.90
6     2025-07    1189141.85            1001841.95
7     2025-08     941542.45            1189141.85
8     2025-09     855849.30             941542.45
9     2025-10    1478657.55             855849.30
10    2025-11    1441314.65            1478657.55
11    2025-12    1112351.80            1441314.65

In [119]:
# Calculate monthly revenue growth percentage
monthly_summary['Growth_%'] = ((monthly_summary['Sales_Amount'] - monthly_summary['Previous_Month_Sales']) / monthly_summary['Previous_Month_Sales']) * 100
 
monthly_summary
monthly_summary.loc[
    monthly_summary['Previous_Month_Sales'].isna(),
    'Growth_%'
] = float('nan')

monthly_summary

   Year_Month  Sales_Amount  Previous_Month_Sales   Growth_%
0     2025-01     869432.00                   NaN        NaN
1     2025-02     826025.00             869432.00  -4.992570
2     2025-03    1033394.55             826025.00  25.104513
3     2025-04     802252.60            1033394.55 -22.367251
4     2025-05     678614.90             802252.60 -15.411318
5     2025-06    1001841.95             678614.90  47.630409
6     2025-07    1189141.85            1001841.95  18.695554
7     2025-08     941542.45            1189141.85 -20.821688
8     2025-09     855849.30             941542.45  -9.101358
9     2025-10    1478657.55             855849.30  72.770785
10    2025-11    1441314.65            1478657.55  -2.525460
11    2025-12    1112351.80            1441314.65 -22.823805

In [121]:
Growth =  (monthly_summary['Previous_Month_Sales'].sum() / monthly_summary['Sales_Amount'].sum()) * 100
Growth

90.90503901477256

In [57]:
print(f'''KPI CALCULATIONS:

1) Total Revenue              : {Total_Revenue:.2f}
2) Total Profit               : {Total_Profit:.2f}
3) Total Orders               : {Total_Orders}
4) Total Customers            : {Total_Customers}
5) Average Order Value (AOV)  : {Average_Order_Value:.2f}
6) Profit Margin              : {Profit_Margin:.2f} %
''')

KPI CALCULATIONS:

1) Total Revenue              : 12230418.60
2) Total Profit               : 3448898.36
3) Total Orders               : 4000
4) Total Customers            : 1350
5) Average Order Value (AOV)  : 3057.60
6) Profit Margin              : 28.20 %

In [115]:
# Exclude January because its growth rate is NaN
average_growth = monthly_summary['Growth_%'].mean()

median_growth = monthly_summary['Growth_%'].median()

print(f"Average Monthly Growth: {average_growth:.2f}%")
print(f"Median Monthly Growth: {median_growth:.2f}%")

Average Monthly Growth: 6.01%
Median Monthly Growth: -4.99%