In [12]:
import pandas as pd
import numpy as np
import seaborn as sns

In [13]:
df = pd.read_csv('Fashion_Retail_Sales_Cleaned.csv')

### Removing Inconsistent values

In [15]:
df.columns

Index(['Unnamed: 0', 'Order_ID', 'Order_Date', 'Order_Channel',
       'Payment_Method', 'Customer_ID', 'Customer_Name', 'Gender', 'Age',
       'Age_Group', 'Customer_Type', 'Segment', 'Product_Category',
       'Product_Name', 'Brand', 'Size', 'Color', 'Units_Sold', 'Unit_Price',
       'Discount_%', 'Sales_Amount', 'Cost_Amount', 'City', 'State', 'Region',
       'Return_Status', 'Order_Year', 'Order_Quarter', 'Profit',
       'Profit_Margin_%', 'Order_Month'],
      dtype='object')

In [16]:
price_check = df.groupby(['Brand','Product_Category', 'Product_Name'])['Unit_Price'].agg(['count', 'nunique', 'min', 'max', 'median'])

# filtered rows which will tell us that min and max values to check how much price is varying 
# . Our focus should be on min and max not nunique

In [17]:
price_check

                                              count  nunique     min     max  \
Brand       Product_Category Product_Name
FashionNest Accessories      Backpack            10        1  1699.0  1699.0
                             Cap                 20        2   399.0   449.0
                             Leather Belt         7        2   699.0   799.0
                             Scarf                4        1   449.0   449.0
                             Sling Bag           13        2  1099.0  1199.0
...                                             ...      ...     ...     ...
WearWorks   Trousers         Cargo Trousers      22        1  1299.0  1299.0
                             Chinos               4        1  1199.0  1199.0
                             Formal Trousers      4        1  1299.0  1299.0
                             Jogger Pants        15        1   799.0   799.0
                             Palazzo Pants        3        1   899.0   899.0

                                              median
Brand       Product_Category Product_Name
FashionNest Accessories      Backpack         1699.0
                             Cap               399.0
                             Leather Belt      699.0
                             Scarf             449.0
                             Sling Bag        1099.0
...                                              ...
WearWorks   Trousers         Cargo Trousers   1299.0
                             Chinos           1199.0
                             Formal Trousers  1299.0
                             Jogger Pants      799.0
                             Palazzo Pants     899.0

[478 rows x 5 columns]

In [18]:
price_check_multiple = price_check[price_check['nunique'] > 1]
price_check_multiple

# checked where the we have more than one unit price for same product

                                                   count  nunique     min  \
Brand       Product_Category Product_Name
FashionNest Accessories      Cap                      20        2   399.0
                             Leather Belt              7        2   699.0
                             Sling Bag                13        2  1099.0
                             Socks Pack               21        2   349.0
                             Sunglasses                9        2  1199.0
...                                                  ...      ...     ...
WearWorks   Shirts           Oxford Shirt              7        2  1099.0
                             Printed Resort Shirt      7        2   799.0
            Sweatshirts      Zip-up Hoodie            11        2  1499.0
            T-Shirts         Crop T-Shirt             10        2   499.0
                             Graphic Tee              24        2   499.0

                                                      max  median
Brand       Product_Category Product_Name
FashionNest Accessories      Cap                    449.0   399.0
                             Leather Belt           799.0   699.0
                             Sling Bag             1199.0  1099.0
                             Socks Pack             399.0   349.0
                             Sunglasses            1299.0  1199.0
...                                                   ...     ...
WearWorks   Shirts           Oxford Shirt          1399.0  1099.0
                             Printed Resort Shirt  1199.0   799.0
            Sweatshirts      Zip-up Hoodie         1599.0  1499.0
            T-Shirts         Crop T-Shirt           549.0   499.0
                             Graphic Tee            599.0   499.0

[135 rows x 5 columns]

In [19]:
price_check_multiple.sort_values('max', ascending = False).head(20)

# in this we found first 5 rows suspicious
# Reason : They have major difference in min and max values which is 10x or 100x more than normal unit price

                                                  count  nunique     min  \
Brand       Product_Category Product_Name
ModeStreet  Shirts           Casual Shirt            21        2  1199.0
UrbanEdge   T-Shirts         Basic Crew Neck Tee     31        3   449.0
UrbanThread Jackets          Bomber Jacket           10        3  2799.0
UrbanEdge   Trousers         Chinos                   6        2  1599.0
ModeStreet  Sweatshirts      Hoodie                  16        3  1499.0
VogueLine   Jackets          Puffer Jacket            7        2  3299.0
            Shoes            Running Shoes           13        2  2999.0
            Dresses          Party Wear Dress         3        2  2899.0
TrendAura   Shoes            Running Shoes           15        2  2999.0
StreetMode  Jackets          Puffer Jacket           13        2  3199.0
VogueLine   Shoes            Casual Sneakers         12        2  2499.0
TrendAura   Shoes            Formal Shoes             5        2  2999.0
VogueLine   Jackets          Denim Jacket            11        2  2599.0
UrbanThread Shoes            Running Shoes            4        2  2999.0
UrbanEdge   Shoes            Formal Shoes             5        2  2899.0
VogueLine   Shoes            Loafers                  6        2  2499.0
StreetMode  Shoes            Running Shoes           10        2  2699.0
FashionNest Dresses          Party Wear Dress         8        2  2499.0
StreetMode  Jackets          Bomber Jacket           15        2  2499.0
VogueLine   Jackets          Windcheater              6        2  1999.0

                                                       max  median
Brand       Product_Category Product_Name
ModeStreet  Shirts           Casual Shirt         119900.0  1199.0
UrbanEdge   T-Shirts         Basic Crew Neck Tee   99999.0   549.0
UrbanThread Jackets          Bomber Jacket         28990.0  2899.0
UrbanEdge   Trousers         Chinos                15990.0  1599.0
ModeStreet  Sweatshirts      Hoodie                15990.0  1599.0
VogueLine   Jackets          Puffer Jacket          4699.0  4699.0
            Shoes            Running Shoes          3899.0  3899.0
            Dresses          Party Wear Dress       3699.0  3699.0
TrendAura   Shoes            Running Shoes          3599.0  3599.0
StreetMode  Jackets          Puffer Jacket          3299.0  3199.0
VogueLine   Shoes            Casual Sneakers        3199.0  3199.0
TrendAura   Shoes            Formal Shoes           3199.0  3199.0
VogueLine   Jackets          Denim Jacket           3199.0  3199.0
UrbanThread Shoes            Running Shoes          3199.0  3199.0
UrbanEdge   Shoes            Formal Shoes           2999.0  2899.0
VogueLine   Shoes            Loafers                2999.0  2999.0
StreetMode  Shoes            Running Shoes          2999.0  2699.0
FashionNest Dresses          Party Wear Dress       2899.0  2499.0
StreetMode  Jackets          Bomber Jacket          2799.0  2499.0
VogueLine   Jackets          Windcheater            2799.0  2799.0

In [20]:
df[(df['Brand'] == 'ModeStreet') & (df['Product_Category'] == 'Shirts') & (df['Product_Name'] == 'Casual Shirt')
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

            Order_ID       Brand Product_Category  Product_Name  Unit_Price
24    ORD-2025-00025  ModeStreet           Shirts  Casual Shirt      1199.0
103   ORD-2025-00104  ModeStreet           Shirts  Casual Shirt      1199.0
267   ORD-2025-00266  ModeStreet           Shirts  Casual Shirt      1199.0
277   ORD-2025-00276  ModeStreet           Shirts  Casual Shirt      1199.0
363   ORD-2025-00362  ModeStreet           Shirts  Casual Shirt      1199.0
399   ORD-2025-00398  ModeStreet           Shirts  Casual Shirt      1199.0
481   ORD-2025-00480  ModeStreet           Shirts  Casual Shirt      1199.0
757   ORD-2025-00755  ModeStreet           Shirts  Casual Shirt      1199.0
779   ORD-2025-00776  ModeStreet           Shirts  Casual Shirt      1199.0
932   ORD-2025-00929  ModeStreet           Shirts  Casual Shirt      1199.0
1130  ORD-2025-01127  ModeStreet           Shirts  Casual Shirt      1199.0
1535  ORD-2025-01531  ModeStreet           Shirts  Casual Shirt      1199.0
1633  ORD-2025-01627  ModeStreet           Shirts  Casual Shirt      1199.0
1713  ORD-2025-01707  ModeStreet           Shirts  Casual Shirt      1199.0
2035  ORD-2025-02028  ModeStreet           Shirts  Casual Shirt      1199.0
2217  ORD-2025-02209  ModeStreet           Shirts  Casual Shirt    119900.0
2609  ORD-2025-02599  ModeStreet           Shirts  Casual Shirt      1199.0
2910  ORD-2025-02900  ModeStreet           Shirts  Casual Shirt      1199.0
2937  ORD-2025-02927  ModeStreet           Shirts  Casual Shirt      1199.0
3092  ORD-2025-03081  ModeStreet           Shirts  Casual Shirt      1199.0
3611  ORD-2025-03598  ModeStreet           Shirts  Casual Shirt      1199.0

In [23]:
df[(df['Brand'] == 'UrbanEdge' ) & (df['Product_Category'] == 'T-Shirts' ) & (df['Product_Name'] == 'Basic Crew Neck Tee' )
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

,Order_ID,Brand,Product_Category,Product_Name,Unit_Price
133,ORD-2025-00134,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
317,ORD-2025-00316,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
457,ORD-2025-00456,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
635,ORD-2025-00634,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
717,ORD-2025-00716,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
819,ORD-2025-00816,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1058,ORD-2025-01055,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1084,ORD-2025-01081,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1206,ORD-2025-01203,UrbanEdge,T-Shirts,Basic Crew Neck Tee,99999.0
1243,ORD-2025-01240,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1252,ORD-2025-01249,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1791,ORD-2025-01785,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1821,ORD-2025-01815,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
1911,ORD-2025-01905,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2002,ORD-2025-01995,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2113,ORD-2025-02105,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2340,ORD-2025-02331,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2529,ORD-2025-02519,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2539,ORD-2025-02529,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2564,ORD-2025-02554,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2630,ORD-2025-02620,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2631,ORD-2025-02621,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2761,ORD-2025-02751,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2786,ORD-2025-02776,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2829,ORD-2025-02819,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
2950,ORD-2025-02940,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
3138,ORD-2025-03127,UrbanEdge,T-Shirts,Basic Crew Neck Tee,449.0
3562,ORD-2025-03549,UrbanEdge,T-Shirts,Basic Crew Neck Tee,449.0
3565,ORD-2025-03552,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
3701,ORD-2025-03688,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0
3738,ORD-2025-03725,UrbanEdge,T-Shirts,Basic Crew Neck Tee,549.0

In [30]:
df[(df['Brand'] == 'UrbanThread' ) & (df['Product_Category'] == 'Jackets' ) & (df['Product_Name'] == 'Bomber Jacket' )
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]
# UrbanThread	Jackets	Bomber Jacket

            Order_ID        Brand Product_Category   Product_Name  Unit_Price
90    ORD-2025-00091  UrbanThread          Jackets  Bomber Jacket      2899.0
306   ORD-2025-00305  UrbanThread          Jackets  Bomber Jacket      2899.0
398   ORD-2025-00397  UrbanThread          Jackets  Bomber Jacket      2899.0
1081  ORD-2025-01078  UrbanThread          Jackets  Bomber Jacket     28990.0
1322  ORD-2025-01318  UrbanThread          Jackets  Bomber Jacket      2899.0
2494  ORD-2025-02484  UrbanThread          Jackets  Bomber Jacket      2899.0
2781  ORD-2025-02771  UrbanThread          Jackets  Bomber Jacket      2899.0
2908  ORD-2025-02898  UrbanThread          Jackets  Bomber Jacket      2899.0
3769  ORD-2025-03756  UrbanThread          Jackets  Bomber Jacket      2899.0
4004  ORD-2025-03990  UrbanThread          Jackets  Bomber Jacket      2799.0

In [32]:
df[(df['Brand'] == 'UrbanEdge' ) & (df['Product_Category'] == 'Trousers' ) & (df['Product_Name'] == 'Chinos' )
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

            Order_ID      Brand Product_Category Product_Name  Unit_Price
718   ORD-2025-00717  UrbanEdge         Trousers       Chinos      1599.0
756   ORD-2025-00754  UrbanEdge         Trousers       Chinos      1599.0
1711  ORD-2025-01705  UrbanEdge         Trousers       Chinos     15990.0
2045  ORD-2025-02038  UrbanEdge         Trousers       Chinos      1599.0
3125  ORD-2025-03114  UrbanEdge         Trousers       Chinos      1599.0
3681  ORD-2025-03668  UrbanEdge         Trousers       Chinos      1599.0

In [34]:
df[(df['Brand'] == 'ModeStreet' ) & (df['Product_Category'] == 'Sweatshirts' ) & (df['Product_Name'] == 'Hoodie' )
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

# 	Sweatshirts	Hoodie

            Order_ID       Brand Product_Category Product_Name  Unit_Price
425   ORD-2025-00424  ModeStreet      Sweatshirts       Hoodie      1499.0
839   ORD-2025-00836  ModeStreet      Sweatshirts       Hoodie      1499.0
908   ORD-2025-00905  ModeStreet      Sweatshirts       Hoodie      1599.0
1141  ORD-2025-01138  ModeStreet      Sweatshirts       Hoodie      1599.0
1337  ORD-2025-01333  ModeStreet      Sweatshirts       Hoodie      1599.0
1383  ORD-2025-01379  ModeStreet      Sweatshirts       Hoodie      1599.0
1558  ORD-2025-01553  ModeStreet      Sweatshirts       Hoodie      1599.0
1883  ORD-2025-01877  ModeStreet      Sweatshirts       Hoodie      1599.0
3049  ORD-2025-03038  ModeStreet      Sweatshirts       Hoodie      1599.0
3113  ORD-2025-03102  ModeStreet      Sweatshirts       Hoodie     15990.0
3453  ORD-2025-03442  ModeStreet      Sweatshirts       Hoodie      1599.0
3480  ORD-2025-03469  ModeStreet      Sweatshirts       Hoodie      1599.0
3505  ORD-2025-03493  ModeStreet      Sweatshirts       Hoodie      1599.0
3527  ORD-2025-03514  ModeStreet      Sweatshirts       Hoodie      1599.0
3634  ORD-2025-03621  ModeStreet      Sweatshirts       Hoodie      1599.0
3920  ORD-2025-03907  ModeStreet      Sweatshirts       Hoodie      1599.0

In [37]:
df['Typical_Price'] = df.groupby(['Brand', 'Product_Category', 'Product_Name'])['Unit_Price'].transform('median')

In [39]:
df[['Brand', 'Product_Category', 'Product_Name', 'Unit_Price','Typical_Price']].head()

,Brand,Product_Category,Product_Name,Unit_Price,Typical_Price
0,ModeStreet,Trousers,Jogger Pants,1099.0,1099.0
1,TrendAura,Sweatshirts,Crewneck Sweatshirt,1599.0,1599.0
2,StreetMode,T-Shirts,Basic Crew Neck Tee,449.0,449.0
3,StreetMode,Accessories,Scarf,449.0,449.0
4,UrbanThread,Accessories,Sling Bag,1199.0,1199.0

In [41]:
df['Price_Ratio'] = df['Unit_Price'] / df['Typical_Price']

In [43]:
df[['Unit_Price', 'Typical_Price', 'Price_Ratio']].sort_values('Price_Ratio', ascending = False).head(20)

      Unit_Price  Typical_Price  Price_Ratio
1206     99999.0          549.0   182.147541
2217    119900.0         1199.0   100.000000
1711     15990.0         1599.0    10.000000
1081     28990.0         2899.0    10.000000
3113     15990.0         1599.0    10.000000
1348      2499.0         1599.0     1.562852
1477      1199.0          799.0     1.500626
3214      1499.0         1099.0     1.363967
1820      1899.0         1399.0     1.357398
2271       399.0          299.0     1.334448
1547      1699.0         1299.0     1.307929
2463      1399.0         1099.0     1.272975
2608      1399.0         1099.0     1.272975
1548      1399.0         1099.0     1.272975
2141      1499.0         1199.0     1.250209
1162      1699.0         1399.0     1.214439
2625      1699.0         1399.0     1.214439
2053       599.0          499.0     1.200401
2622       599.0          499.0     1.200401
1929      1199.0          999.0     1.200200

In [45]:
df[df['Price_Ratio'] > 2][
    ['Brand', 'Product_Category', 'Product_Name',
     'Unit_Price', 'Typical_Price', 'Price_Ratio']
].sort_values('Price_Ratio', ascending=False)

# How many records have a price ratio greater than 2×?

,Brand,Product_Category,Product_Name,Unit_Price,Typical_Price,Price_Ratio
1206,UrbanEdge,T-Shirts,Basic Crew Neck Tee,99999.0,549.0,182.147541
2217,ModeStreet,Shirts,Casual Shirt,119900.0,1199.0,100.000000
1081,UrbanThread,Jackets,Bomber Jacket,28990.0,2899.0,10.000000
1711,UrbanEdge,Trousers,Chinos,15990.0,1599.0,10.000000
3113,ModeStreet,Sweatshirts,Hoodie,15990.0,1599.0,10.000000

In [47]:
df.loc[df['Price_Ratio'] > 2, 'Unit_Price'] = df.loc[df['Price_Ratio'] > 2, 'Typical_Price']

In [49]:
df[df['Price_Ratio'] > 2][
    ['Order_ID', 'Unit_Price', 'Typical_Price', 'Price_Ratio']
]

            Order_ID  Unit_Price  Typical_Price  Price_Ratio
1081  ORD-2025-01078      2899.0         2899.0    10.000000
1206  ORD-2025-01203       549.0          549.0   182.147541
1711  ORD-2025-01705      1599.0         1599.0    10.000000
2217  ORD-2025-02209      1199.0         1199.0   100.000000
3113  ORD-2025-03102      1599.0         1599.0    10.000000

In [51]:
df['Price_Ratio'] = df['Unit_Price'] / df['Typical_Price']

In [53]:
df[df['Order_ID'].isin([
    'ORD-2025-01078',
    'ORD-2025-01203',
    'ORD-2025-01705',
    'ORD-2025-02209',
    'ORD-2025-03102'
])][
    ['Order_ID', 'Unit_Price', 'Typical_Price', 'Price_Ratio']
]

            Order_ID  Unit_Price  Typical_Price  Price_Ratio
1081  ORD-2025-01078      2899.0         2899.0          1.0
1206  ORD-2025-01203       549.0          549.0          1.0
1711  ORD-2025-01705      1599.0         1599.0          1.0
2217  ORD-2025-02209      1199.0         1199.0          1.0
3113  ORD-2025-03102      1599.0         1599.0          1.0

In [55]:
df['Price_Ratio'].describe()

count    4015.000000
mean        1.000006
std         0.037711
min         0.100000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.562852
Name: Price_Ratio, dtype: float64

In [57]:
df[df['Price_Ratio'] < 0.5][
    ['Brand', 'Product_Category', 'Product_Name',
     'Unit_Price', 'Typical_Price', 'Price_Ratio']
].sort_values('Price_Ratio')

,Brand,Product_Category,Product_Name,Unit_Price,Typical_Price,Price_Ratio
809,TrendAura,Accessories,Socks Pack,49.9,499.0,0.1

In [59]:
df[
    (df['Brand'] == 'TrendAura') &
    (df['Product_Category'] == 'Accessories') &
    (df['Product_Name'] == 'Socks Pack')
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

            Order_ID      Brand Product_Category Product_Name  Unit_Price
809   ORD-2025-00806  TrendAura      Accessories   Socks Pack        49.9
1009  ORD-2025-01006  TrendAura      Accessories   Socks Pack       499.0
1648  ORD-2025-01642  TrendAura      Accessories   Socks Pack       499.0
1654  ORD-2025-01648  TrendAura      Accessories   Socks Pack       499.0
1946  ORD-2025-01940  TrendAura      Accessories   Socks Pack       499.0
1949  ORD-2025-01943  TrendAura      Accessories   Socks Pack       499.0
1994  ORD-2025-01987  TrendAura      Accessories   Socks Pack       499.0
2177  ORD-2025-02169  TrendAura      Accessories   Socks Pack       499.0
2904  ORD-2025-02894  TrendAura      Accessories   Socks Pack       499.0
2974  ORD-2025-02964  TrendAura      Accessories   Socks Pack       499.0
3561  ORD-2025-03548  TrendAura      Accessories   Socks Pack       499.0

In [61]:
df.loc[df['Price_Ratio'] < 0.5, 'Unit_Price'] = df.loc[
    df['Price_Ratio'] < 0.5, 'Typical_Price'
]

In [63]:
df['Price_Ratio'] = df['Unit_Price'] / df['Typical_Price']

In [65]:
df[
    (df['Brand'] == 'TrendAura') &
    (df['Product_Category'] == 'Accessories') &
    (df['Product_Name'] == 'Socks Pack')
][['Order_ID', 'Brand', 'Product_Category', 'Product_Name', 'Unit_Price']]

            Order_ID      Brand Product_Category Product_Name  Unit_Price
809   ORD-2025-00806  TrendAura      Accessories   Socks Pack       499.0
1009  ORD-2025-01006  TrendAura      Accessories   Socks Pack       499.0
1648  ORD-2025-01642  TrendAura      Accessories   Socks Pack       499.0
1654  ORD-2025-01648  TrendAura      Accessories   Socks Pack       499.0
1946  ORD-2025-01940  TrendAura      Accessories   Socks Pack       499.0
1949  ORD-2025-01943  TrendAura      Accessories   Socks Pack       499.0
1994  ORD-2025-01987  TrendAura      Accessories   Socks Pack       499.0
2177  ORD-2025-02169  TrendAura      Accessories   Socks Pack       499.0
2904  ORD-2025-02894  TrendAura      Accessories   Socks Pack       499.0
2974  ORD-2025-02964  TrendAura      Accessories   Socks Pack       499.0
3561  ORD-2025-03548  TrendAura      Accessories   Socks Pack       499.0

In [67]:
df[df['Price_Ratio'] != 1][
    ['Brand', 'Product_Category', 'Product_Name',
     'Unit_Price', 'Typical_Price', 'Price_Ratio']
].sort_values('Price_Ratio').head(30)

,Brand,Product_Category,Product_Name,Unit_Price,Typical_Price,Price_Ratio
1794,VogueLine,Trousers,Cargo Trousers,1499.0,2199.0,0.681673
2865,VogueLine,T-Shirts,Oversized T-Shirt,699.0,999.0,0.699700
1154,TrendAura,T-Shirts,Oversized T-Shirt,699.0,999.0,0.699700
3201,VogueLine,Jackets,Puffer Jacket,3299.0,4699.0,0.702064
3971,VogueLine,Shirts,Linen Shirt,1499.0,2099.0,0.714150
3782,VogueLine,Shirts,Linen Shirt,1499.0,2099.0,0.714150
3607,VogueLine,Jackets,Windcheater,1999.0,2799.0,0.714184
2585,TrendAura,T-Shirts,Graphic Tee,599.0,799.0,0.749687
3935,VogueLine,Shoes,Running Shoes,2999.0,3899.0,0.769172
2007,StyleCraft,T-Shirts,Oversized T-Shirt,699.0,899.0,0.777531
2795,VogueLine,Shoes,Casual Sneakers,2499.0,3199.0,0.781182
2368,VogueLine,Dresses,Party Wear Dress,2899.0,3699.0,0.783725
2190,TrendAura,T-Shirts,Crop T-Shirt,549.0,699.0,0.785408
903,VogueLine,Trousers,Chinos,1499.0,1899.0,0.789363
1736,VogueLine,Trousers,Chinos,1499.0,1899.0,0.789363
3892,VogueLine,Shirts,Printed Resort Shirt,1199.0,1499.0,0.799867
134,UrbanEdge,Sweatshirts,Zip-up Hoodie,1599.0,1999.0,0.799900
3251,VogueLine,Jackets,Denim Jacket,2599.0,3199.0,0.812441
3562,UrbanEdge,T-Shirts,Basic Crew Neck Tee,449.0,549.0,0.817851
3138,UrbanEdge,T-Shirts,Basic Crew Neck Tee,449.0,549.0,0.817851
278,TrendAura,Jeans,Baggy Jeans,1899.0,2299.0,0.826011
2224,VogueLine,Dresses,Floral Midi Dress,1899.0,2299.0,0.826011
167,VogueLine,Dresses,Floral Midi Dress,1899.0,2299.0,0.826011
1373,VogueLine,Dresses,Floral Midi Dress,1899.0,2299.0,0.826011
3494,UrbanEdge,Trousers,Cargo Trousers,1499.0,1799.0,0.833241
2835,VogueLine,Shoes,Loafers,2499.0,2999.0,0.833278
2923,TrendAura,Shoes,Running Shoes,2999.0,3599.0,0.833287
3866,TrendAura,Shoes,Running Shoes,2999.0,3599.0,0.833287
3378,TrendAura,Dresses,Casual Dress,1599.0,1899.0,0.842022
388,UrbanEdge,T-Shirts,Graphic Tee,599.0,699.0,0.856938

In [69]:
df[df['Unit_Price'] % 1 != 0][
    ['Brand', 'Product_Category', 'Product_Name', 'Unit_Price']
]

Empty DataFrame
Columns: [Brand, Product_Category, Product_Name, Unit_Price]
Index: []

In [71]:
df[df['Discount_%'] < 0][['Unit_Price', 'Discount_%', 'Sales_Amount']]

      Unit_Price   Discount_%  Sales_Amount
16         549.0  -750.000000       9333.00
2206      1899.0  -700.000000      15192.00
2554      1299.0  -100.000000       2598.00
2585       599.0   -33.388982        799.00
2626       899.0 -1700.000000      16182.00
3673      1599.0  -425.000000       8394.75

In [73]:
df[df['Units_Sold']<1]

Empty DataFrame
Columns: [Unnamed: 0, Order_ID, Order_Date, Order_Channel, Payment_Method, Customer_ID, Customer_Name, Gender, Age, Age_Group, Customer_Type, Segment, Product_Category, Product_Name, Brand, Size, Color, Units_Sold, Unit_Price, Discount_%, Sales_Amount, Cost_Amount, City, State, Region, Return_Status, Order_Year, Order_Quarter, Profit, Profit_Margin_%, Order_Month, Typical_Price, Price_Ratio]
Index: []

[0 rows x 33 columns]

In [75]:
df[df['Discount_%'] < 0][
    ['Product_Name', 'Unit_Price', 'Units_Sold', 'Discount_%', 'Sales_Amount']
]

              Product_Name  Unit_Price  Units_Sold   Discount_%  Sales_Amount
16              Socks Pack       549.0         2.0  -750.000000       9333.00
2206              Backpack      1899.0         1.0  -700.000000      15192.00
2554           Linen Shirt      1299.0         1.0  -100.000000       2598.00
2585           Graphic Tee       599.0         1.0   -33.388982        799.00
2626          Leather Belt       899.0         1.0 -1700.000000      16182.00
3673  Oversized Sweatshirt      1599.0         1.0  -425.000000       8394.75

In [77]:
df['Discount_%'].describe()

count    4015.000000
mean       16.181372
std        34.635759
min     -1700.000000
25%        10.000000
50%        20.000000
75%        25.000000
max        40.000000
Name: Discount_%, dtype: float64

In [79]:
df['Discount_%'].value_counts().sort_index()

Discount_%
-1700.000000      1
-750.000000       1
-700.000000       1
-425.000000       1
-100.000000       1
-33.388982        1
 0.000000       769
 5.000000         2
 5.000000       150
 5.000000        11
 10.000000       21
 10.000000      440
 10.000000       19
 15.000000       33
 15.000000      485
 15.000000       30
 17.655103        1
 20.000000      706
 20.000000       23
 20.585639        1
 25.000000      474
 30.000000       11
 30.000000      403
 30.000000       26
 33.355593        1
 35.000000      191
 35.000000        5
 40.000000        7
 40.000000      200
Name: count, dtype: int64

In [81]:
df[~df['Discount_%'].isin([0, 5, 10, 15, 20, 25, 30, 35, 40])][
    ['Product_Name', 'Unit_Price', 'Units_Sold', 'Discount_%', 'Sales_Amount']
]

             Product_Name  Unit_Price  Units_Sold  Discount_%  Sales_Amount
2     Basic Crew Neck Tee       449.0         4.0        30.0       1257.20
16             Socks Pack       549.0         2.0      -750.0       9333.00
31           Polo T-Shirt      1099.0         7.0        15.0       6539.05
32    Crewneck Sweatshirt      1099.0         2.0        10.0       1978.20
58         Cargo Trousers      1599.0         1.0        10.0       1439.10
...                   ...         ...         ...         ...           ...
3863              Loafers      1899.0         1.0        40.0       1139.40
3872        Zip-up Hoodie      1999.0         3.0        10.0       5397.30
3904        Zip-up Hoodie      1899.0         1.0        15.0       1614.15
3920               Hoodie      1599.0         1.0        15.0       1359.15
3954          Baggy Jeans      1399.0         3.0        15.0       3567.45

[197 rows x 5 columns]

In [83]:
df[~df['Discount_%'].isin([0, 5, 10, 15, 20, 25, 30, 35, 40])]['Discount_%'].value_counts().sort_index()

Discount_%
-1700.000000     1
-750.000000      1
-700.000000      1
-425.000000      1
-100.000000      1
-33.388982       1
 5.000000        2
 5.000000       11
 10.000000      21
 10.000000      19
 15.000000      33
 15.000000      30
 17.655103       1
 20.000000      23
 20.585639       1
 30.000000      11
 30.000000      26
 33.355593       1
 35.000000       5
 40.000000       7
Name: count, dtype: int64

In [85]:
df[df['Discount_%'].between(4.9, 5.1)]['Discount_%'].unique()

array([5., 5., 5.])

In [87]:
df[~df['Discount_%'].isin([0, 5, 10, 15, 20, 25, 30, 35, 40])]['Discount_%'].unique()

array([   30.        ,  -750.        ,    15.        ,    10.        ,
          10.        ,    40.        ,    30.        ,    35.        ,
           5.        ,    15.        ,    20.        ,     5.        ,
          17.6551034 ,  -700.        ,  -100.        ,   -33.38898164,
          33.35559265, -1700.        ,    20.58563861,  -425.        ])

In [89]:
df[~df['Discount_%'].isin([0, 5, 10, 15, 20, 25, 30, 35, 40])][
    ['Product_Name', 'Unit_Price', 'Units_Sold', 'Discount_%', 'Sales_Amount']
].sort_values('Discount_%')

              Product_Name  Unit_Price  Units_Sold  Discount_%  Sales_Amount
2626          Leather Belt       899.0         1.0     -1700.0      16182.00
16              Socks Pack       549.0         2.0      -750.0       9333.00
2206              Backpack      1899.0         1.0      -700.0      15192.00
3673  Oversized Sweatshirt      1599.0         1.0      -425.0       8394.75
2554           Linen Shirt      1299.0         1.0      -100.0       2598.00
...                    ...         ...         ...         ...           ...
168        Casual Sneakers      2699.0         1.0        40.0       1619.40
3863               Loafers      1899.0         1.0        40.0       1139.40
2834        Slim Fit Jeans      1799.0         1.0        40.0       1079.40
91         Casual Sneakers      2699.0         1.0        40.0       1619.40
473            Windcheater      1999.0         1.0        40.0       1199.40

[197 rows x 5 columns]

In [91]:
valid_discounts = [0, 5, 10, 15, 20, 25, 30, 35, 40]

mask = ~df['Discount_%'].apply(
    lambda x: any(abs(x - d) < 0.0001 for d in valid_discounts)
)

df[mask][
    ['Product_Name', 'Unit_Price', 'Units_Sold', 'Discount_%', 'Sales_Amount']
]

              Product_Name  Unit_Price  Units_Sold   Discount_%  Sales_Amount
16              Socks Pack       549.0         2.0  -750.000000       9333.00
903                 Chinos      1499.0         2.0    17.655103       2468.70
2206              Backpack      1899.0         1.0  -700.000000      15192.00
2554           Linen Shirt      1299.0         1.0  -100.000000       2598.00
2585           Graphic Tee       599.0         1.0   -33.388982        799.00
2622           Graphic Tee       599.0         3.0    33.355593       1197.60
2626          Leather Belt       899.0         1.0 -1700.000000      16182.00
3502        Slim Fit Jeans      1699.0         1.0    20.585639       1349.25
3673  Oversized Sweatshirt      1599.0         1.0  -425.000000       8394.75

In [93]:
valid_discounts = [0, 5, 10, 15, 20, 25, 30, 35, 40]

In [95]:
invalid_discount = ~df['Discount_%'].between(0, 40) | (df['Discount_%'] % 5 != 0)

In [97]:
df.loc[
    invalid_discount & (df['Discount_%'] >= 0),
    'Discount_%'
] = (
    df.loc[
        invalid_discount & (df['Discount_%'] >= 0),
        'Discount_%'
    ] / 5
).round() * 5

In [99]:
def get_product_discount(row):
    product_discounts = df.loc[
        (df['Product_Name'] == row['Product_Name']) &
        (~invalid_discount),
        'Discount_%'
    ]
    
    if len(product_discounts) > 0:
        return product_discounts.mode().iloc[0]
    
    return df.loc[~invalid_discount, 'Discount_%'].mode().iloc[0]

In [101]:
negative_discount = df['Discount_%'] < 0

df.loc[negative_discount, 'Discount_%'] = df.loc[
    negative_discount
].apply(get_product_discount, axis=1)

In [103]:
df['Discount_%'].value_counts().sort_index()

Discount_%
0.0     771
5.0     163
10.0    480
15.0    548
20.0    735
25.0    474
30.0    440
35.0    197
40.0    207
Name: count, dtype: int64

In [105]:
df['Discount_%'].between(0, 40).all()

True

In [107]:
(df['Discount_%'] % 5 == 0).all()

True

In [109]:
df['Sales_Amount'] = (
    df['Unit_Price']
    * df['Units_Sold']
    * (1 - df['Discount_%'] / 100)
).round(2)

In [111]:
df['Discount_%'].describe()

count    4015.000000
mean       17.125778
std        11.775401
min         0.000000
25%        10.000000
50%        20.000000
75%        25.000000
max        40.000000
Name: Discount_%, dtype: float64

In [113]:
        df['Sales_Amount'].isna().sum()

0

In [115]:
df[['Unit_Price', 'Units_Sold', 'Discount_%', 'Sales_Amount']].head()

   Unit_Price  Units_Sold  Discount_%  Sales_Amount
0      1099.0         1.0         0.0       1099.00
1      1599.0         1.0        35.0       1039.35
2       449.0         4.0        30.0       1257.20
3       449.0         3.0         5.0       1279.65
4      1199.0         2.0        20.0       1918.40

In [117]:
df['Profit'] = df['Sales_Amount'] - df['Unit_Price']

In [119]:
df['Profit_Margin_%'] = (
    df['Profit'] / df['Sales_Amount'] * 100
).round(2)

### Segment Column Inspection

In [121]:
df['Segment'].value_counts(dropna = False)

Segment
B2C        3411
B2B         344
Unknown     260
Name: count, dtype: int64

In [124]:
multipleSeg = df.groupby('Customer_ID')['Segment'].nunique()
multipleSeg.loc[lambda x : x>1]

# there are total 196 customers who has atmost 2 segments. 
# there are no customers with 3 different segments

Customer_ID
CUST-0003    2
CUST-0022    2
CUST-0023    2
CUST-0025    2
CUST-0033    2
            ..
CUST-1093    2
CUST-1105    2
CUST-1108    2
CUST-1165    2
CUST-1319    2
Name: Segment, Length: 196, dtype: int64

In [125]:
multiple_customers = multipleSeg[multipleSeg > 1].index 
#this will keep the id's of customers who has more than one segment

df[df['Customer_ID'].isin(multiple_customers)][['Customer_ID','Segment']].sort_values('Customer_ID')
# checkes that which customers belongs to multiple customers then prints customerid and segment of this
# where sorting is done on the basis of CUstomerID

     Customer_ID  Segment
2      CUST-0003      B2C
618    CUST-0003  Unknown
780    CUST-0003      B2C
872    CUST-0003      B2C
953    CUST-0003      B2C
...          ...      ...
2717   CUST-1165      B2C
3015   CUST-1165  Unknown
3901   CUST-1319      B2C
4010   CUST-1319  Unknown
3726   CUST-1319      B2C

[1069 rows x 2 columns]

In [128]:
Known_segments = df[df['Segment'].isin(['B2C','B2B'])]

In [130]:
segmentcounts = Known_segments.groupby('Customer_ID')['Segment'].nunique()

In [132]:
segmentcounts[segmentcounts > 1]

Series([], Name: Segment, dtype: int64)

In [134]:
mask = df['Segment'].eq('Unknown')

customer_segments = df[df['Segment'].isin(['B2B','B2C'])].groupby('Customer_ID')['Segment'].first()

df.loc[mask, 'Segment'] = (df.loc[mask, 'Customer_ID'].map(customer_segments).fillna('Unknown'))

In [136]:
df['Segment'].value_counts(dropna=False)

Segment
B2C        3616
B2B         366
Unknown      33
Name: count, dtype: int64

In [138]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Order_Date'].dtype

dtype('<M8[ns]')

In [140]:
# 1. Dataset overview
print("========== DATASET OVERVIEW ==========")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())


# 2. Missing values
print("\n========== MISSING VALUES ==========")
print(df.isnull().sum()[df.isnull().sum() > 0])


# 3. Data types
print("\n========== DATA TYPES ==========")
print(df.dtypes)


# 4. Unique values in categorical columns
categorical_cols = [
    'Brand',
    'Product_Category',
    'Product_Name',
    'City',
    'Segment'
]

print("\n========== CATEGORICAL OVERVIEW ==========")

for col in categorical_cols:
    print(f"\n{col}")
    print("Unique values:", df[col].nunique(dropna=False))
    print(df[col].value_counts(dropna=False).head(20))


# 5. Numeric column validation
print("\n========== NUMERIC VALIDATION ==========")

numeric_cols = [
    'Unit_Price',
    'Units_Sold',
    'Discount_%',
    'Sales_Amount',
    'Profit',
    'Profit_Margin_%'
]

print(df[numeric_cols].describe().T)

print("\nNon-positive unit prices:")
print((df['Unit_Price'] <= 0).sum())

print("\nZero or negative quantities:")
print((df['Units_Sold'] <= 0).sum())

print("\nDiscounts outside 0–40:")
print((~df['Discount_%'].between(0, 40)).sum())


# 6. Date validation
print("\n========== DATE VALIDATION ==========")

print("Missing order dates:", df['Order_Date'].isna().sum())

print("\nOrder years inconsistent with Order_Date:")
print(
    (
        df['Order_Year'].notna()
        & df['Order_Date'].notna()
        & (df['Order_Year'] != df['Order_Date'].dt.year)
    ).sum()
)

print("\nOrder months inconsistent with Order_Date:")
print(
    (
        df['Order_Month'].notna()
        & df['Order_Date'].notna()
        & (df['Order_Month'] != df['Order_Date'].dt.month)
    ).sum()
)

print("\nOrder quarters inconsistent with Order_Date:")
print(
    (
        df['Order_Quarter'].notna()
        & df['Order_Date'].notna()
        & (
            df['Order_Quarter']
            != 'Q' + df['Order_Date'].dt.quarter.astype(str)
        )
    ).sum()
)


# 7. Formula consistency
print("\n========== FORMULA VALIDATION ==========")

expected_sales = (
    df['Unit_Price']
    * df['Units_Sold']
    * (1 - df['Discount_%'] / 100)
)

print(
    "Sales_Amount mismatches:",
    (~np.isclose(
        df['Sales_Amount'],
        expected_sales,
        rtol=1e-5,
        atol=0.01,
        equal_nan=True
    )).sum()
)

expected_profit = df['Sales_Amount'] - df['Unit_Price']

print(
    "Profit mismatches:",
    (~np.isclose(
        df['Profit'],
        expected_profit,
        rtol=1e-5,
        atol=0.01,
        equal_nan=True
    )).sum()
)

expected_margin = df['Profit'] / df['Sales_Amount'] * 100

print(
    "Profit margin mismatches:",
    (~np.isclose(
        df['Profit_Margin_%'],
        expected_margin,
        rtol=1e-5,
        atol=0.01,
        equal_nan=True
    )).sum()
)


# 8. Helper columns
print("\n========== HELPER COLUMNS ==========")

helper_cols = ['Typical_Price', 'Price_Ratio']

print("Helper columns still present:")
print([col for col in helper_cols if col in df.columns])

========== DATASET OVERVIEW ==========
Rows: 4015
Columns: 33
Duplicate rows: 0

========== MISSING VALUES ==========
Series([], dtype: int64)

========== DATA TYPES ==========
Unnamed: 0                   int64
Order_ID                    object
Order_Date          datetime64[ns]
Order_Channel               object
Payment_Method              object
Customer_ID                 object
Customer_Name               object
Gender                      object
Age                          int64
Age_Group                   object
Customer_Type               object
Segment                     object
Product_Category            object
Product_Name                object
Brand                       object
Size                        object
Color                       object
Units_Sold                 float64
Unit_Price                 float64
Discount_%                 float64
Sales_Amount               float64
Cost_Amount                float64
City                        object
State                       object
Region                      object
Return_Status               object
Order_Year                   int64
Order_Quarter               object
Profit                     float64
Profit_Margin_%            float64
Order_Month                 object
Typical_Price              float64
Price_Ratio                float64
dtype: object

========== CATEGORICAL OVERVIEW ==========

Brand
Unique values: 10
Brand
UrbanEdge      539
ModeStreet     478
StreetMode     449
StyleCraft     439
FashionNest    413
ThreadLab      412
WearWorks      332
TrendAura      327
UrbanThread    322
VogueLine      304
Name: count, dtype: int64

Product_Category
Unique values: 9
Product_Category
T-Shirts       827
Accessories    590
Shirts         432
Sweatshirts    429
Shoes          425
Jeans          389
Trousers       360
Dresses        291
Jackets        272
Name: count, dtype: int64

Product_Name
Unique values: 52
Product_Name
Oversized T-Shirt      266
Hoodie                 193
Graphic Tee            182
Basic Crew Neck Tee    178
Casual Sneakers        162
Cap                    143
Jogger Pants           120
Casual Shirt           118
Cargo Trousers         116
Straight Fit Jeans     114
Baggy Jeans            113
Polo T-Shirt           107
Socks Pack              99
Linen Shirt             95
Sandals                 90
Sling Bag               88
Running Shoes           87
Bomber Jacket           86
Crewneck Sweatshirt     82
Zip-up Hoodie           81
Name: count, dtype: int64

City
Unique values: 14
City
Mumbai       702
Bangalore    627
Delhi        531
Pune         493
Hyderabad    395
Chennai      333
Kolkata      281
Ahmedabad    198
Surat        129
Jaipur       125
Indore       114
Lucknow       71
New Delhi     10
Madras         6
Name: count, dtype: int64

Segment
Unique values: 3
Segment
B2C        3616
B2B         366
Unknown      33
Name: count, dtype: int64

========== NUMERIC VALIDATION ==========
                  count         mean          std      min     25%     50%  \
Unit_Price       4015.0  1458.750934   811.006705   299.00  799.00  1399.0
Units_Sold       4015.0     2.867497     4.986167     1.00    1.00     1.0
Discount_%       4015.0    17.125778    11.775401     0.00   10.00    20.0
Sales_Amount     4015.0  3055.328767  5643.305782   194.35  998.00  1519.2
Profit           4015.0  1596.577833  5560.331191 -2439.60 -269.85     0.0
Profit_Margin_%  4015.0     9.502909    43.909451   -66.67  -25.00     0.0

                     75%      max
Unit_Price       1799.00   8499.0
Units_Sold          2.00     30.0
Discount_%         25.00     40.0
Sales_Amount     2598.00  64936.8
Profit           1028.40  62137.8
Profit_Margin_%    47.37     96.3

Non-positive unit prices:
0

Zero or negative quantities:
0

Discounts outside 0–40:
0

========== DATE VALIDATION ==========
Missing order dates: 0

Order years inconsistent with Order_Date:
0

Order months inconsistent with Order_Date:
4015

Order quarters inconsistent with Order_Date:
100

========== FORMULA VALIDATION ==========
Sales_Amount mismatches: 0
Profit mismatches: 0
Profit margin mismatches: 0

========== HELPER COLUMNS ==========
Helper columns still present:
['Typical_Price', 'Price_Ratio']

In [141]:
print(df['Order_Month'].dtype)
print(df['Order_Month'].unique())

object
['January' 'July' 'February' 'March' 'April' 'May' 'June' 'August'
 'September' 'October' 'November' 'December']

In [144]:
(df['Order_Month'] != df['Order_Date'].dt.month_name()).sum()

0

In [146]:
quarter_mismatch = df[
    df['Order_Quarter'] !=
    'Q' + df['Order_Date'].dt.quarter.astype(str)
]

quarter_mismatch[
    ['Order_Date', 'Order_Quarter']
].head(20)

# What this code does
# Calculates the correct quarter from Order_Date.
# Compares it with the existing Order_Quarter.
# Displays up to 20 records where the values differ.

    Order_Date Order_Quarter
62  2025-07-22            Q0
63  2025-07-22            Q0
92  2025-07-22            Q0
115 2025-07-22            Q0
148 2025-07-22            Q0
203 2025-07-22            Q0
265 2025-07-22            Q0
274 2025-07-22            Q0
311 2025-07-22            Q0
346 2025-07-22            Q0
539 2025-07-22            Q0
586 2025-07-22            Q0
590 2025-07-22            Q0
592 2025-07-22            Q0
699 2025-07-22            Q0
704 2025-07-22            Q0
769 2025-07-22            Q0
800 2025-07-22            Q0
929 2025-07-22            Q0
950 2025-07-22            Q0

In [148]:
df['Order_Quarter'] = 'Q' + df['Order_Date'].dt.quarter.astype(str)

In [150]:
quarter_mismatch = df[
    df['Order_Quarter'] !=
    'Q' + df['Order_Date'].dt.quarter.astype(str)
]

quarter_mismatch[
    ['Order_Date', 'Order_Quarter']
].head(20)

Empty DataFrame
Columns: [Order_Date, Order_Quarter]
Index: []

In [152]:
df['City'] = df['City'].replace({
    'Bangalore': 'Bengaluru',
    'New Delhi': 'Delhi',
    'Madras': 'Chennai'
})

In [154]:
df['City'].value_counts()

City
Mumbai       702
Bengaluru    627
Delhi        541
Pune         493
Hyderabad    395
Chennai      339
Kolkata      281
Ahmedabad    198
Surat        129
Jaipur       125
Indore       114
Lucknow       71
Name: count, dtype: int64

In [156]:
df['Unnamed: 0'].head(10)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Unnamed: 0, dtype: int64

In [158]:
df.drop(
    columns=['Unnamed: 0', 'Typical_Price', 'Price_Ratio'],
    inplace=True
)

In [160]:
df.shape

(4015, 30)

In [162]:
df = df.drop_duplicates()

In [164]:
# 1. Dataset dimensions
print("Dataset shape:", df.shape)

# 2. Duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# 3. Missing values
print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# 4. Check segment values
print("\nSegment distribution:")
print(df['Segment'].value_counts(dropna=False))

# 5. Check discounts
print("\nDiscount values:")
print(sorted(df['Discount_%'].unique()))

# 6. Check date-related columns
print("\nOrder years:")
print(df['Order_Year'].value_counts().sort_index())

print("\nOrder months:")
print(df['Order_Month'].value_counts())

print("\nOrder quarters:")
print(df['Order_Quarter'].value_counts().sort_index())

# 7. Check data types
print("\nData types:")
print(df.dtypes)

Dataset shape: (4000, 30)
Duplicate rows: 0

Missing values:
Series([], dtype: int64)

Segment distribution:
Segment
B2C        3603
B2B         364
Unknown      33
Name: count, dtype: int64

Discount values:
[0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0]

Order years:
Order_Year
2025    4000
Name: count, dtype: int64

Order months:
Order_Month
October      477
July         430
November     410
December     382
January      322
August       313
June         307
March        295
May          286
September    272
April        262
February     244
Name: count, dtype: int64

Order quarters:
Order_Quarter
Q1     861
Q2     855
Q3    1015
Q4    1269
Name: count, dtype: int64

Data types:
Order_ID                    object
Order_Date          datetime64[ns]
Order_Channel               object
Payment_Method              object
Customer_ID                 object
Customer_Name               object
Gender                      object
Age                          int64
Age_Group                   object
Customer_Type               object
Segment                     object
Product_Category            object
Product_Name                object
Brand                       object
Size                        object
Color                       object
Units_Sold                 float64
Unit_Price                 float64
Discount_%                 float64
Sales_Amount               float64
Cost_Amount                float64
City                        object
State                       object
Region                      object
Return_Status               object
Order_Year                   int64
Order_Quarter               object
Profit                     float64
Profit_Margin_%            float64
Order_Month                 object
dtype: object

In [166]:
df.shape

(4000, 30)

In [168]:
df['Profit'] = df['Sales_Amount'] - df['Unit_Price']

In [170]:
df = df.copy()

In [172]:
df.loc[:, 'Profit'] = df['Sales_Amount'] - df['Cost_Amount']

In [174]:
df.loc[:, 'Profit_Margin_%'] = (
    df['Profit'] / df['Sales_Amount'] * 100
).round(2)

In [176]:
df[['Sales_Amount', 'Cost_Amount', 'Profit', 'Profit_Margin_%']].head(10)

   Sales_Amount  Cost_Amount  Profit  Profit_Margin_%
0       1099.00       595.08  503.92            45.85
1       1039.35       859.71  179.64            17.28
2       1257.20       930.12  327.08            26.02
3       1279.65       603.18  676.47            52.86
4       1918.40      1195.50  722.90            37.68
5       1347.00       829.12  517.88            38.45
6       1499.00       945.35  553.65            36.93
7       2398.40      1573.70  824.70            34.39
8        359.20       236.43  122.77            34.18
9       1889.30      1759.98  129.32             6.84

In [178]:
df[['Sales_Amount', 'Unit_Price', 'Profit']].head()

   Sales_Amount  Unit_Price  Profit
0       1099.00      1099.0  503.92
1       1039.35      1599.0  179.64
2       1257.20       449.0  327.08
3       1279.65       449.0  676.47
4       1918.40      1199.0  722.90

In [180]:
df[['Unit_Price', 'Units_Sold', 'Discount_%',
    'Sales_Amount', 'Cost_Amount', 'Profit']].head(10)

   Unit_Price  Units_Sold  Discount_%  Sales_Amount  Cost_Amount  Profit
0      1099.0         1.0         0.0       1099.00       595.08  503.92
1      1599.0         1.0        35.0       1039.35       859.71  179.64
2       449.0         4.0        30.0       1257.20       930.12  327.08
3       449.0         3.0         5.0       1279.65       603.18  676.47
4      1199.0         2.0        20.0       1918.40      1195.50  722.90
5       449.0         4.0        25.0       1347.00       829.12  517.88
6      1499.0         1.0         0.0       1499.00       945.35  553.65
7      1499.0         2.0        20.0       2398.40      1573.70  824.70
8       449.0         1.0        20.0        359.20       236.43  122.77
9      2699.0         1.0        30.0       1889.30      1759.98  129.32

In [182]:

expected_profit = df['Sales_Amount'] - df['Cost_Amount']

print(
    "Profit mismatches:",
    (~np.isclose(
        df['Profit'],
        expected_profit,
        atol=0.01
    )).sum()
)

expected_margin = (
    df['Profit'] / df['Sales_Amount'] * 100
)

print(
    "Profit margin mismatches:",
    (~np.isclose(
        df['Profit_Margin_%'],
        expected_margin,
        atol=0.01
    )).sum()
)

Profit mismatches: 0
Profit margin mismatches: 0

In [184]:

categorical_columns = [
    'Gender',
    'Age_Group',
    'Customer_Type',
    'Order_Channel',
    'Payment_Method',
    'Product_Category',
    'Product_Name',
    'Brand',
    'Size',
    'Color',
    'State',
    'Region',
    'Return_Status'
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(sorted(df[col].dropna().astype(str).unique()))

Gender:
['Female', 'Male', 'Other']

Age_Group:
['18-24', '25-34', '35-44', '45-55']

Customer_Type:
['One-time Customer', 'Repeat Customer']

Order_Channel:
['Mobile App', 'Physical Store', 'Website']

Payment_Method:
['Cash on Delivery', 'Credit Card', 'Debit Card', 'Net Banking', 'UPI']

Product_Category:
['Accessories', 'Dresses', 'Jackets', 'Jeans', 'Shirts', 'Shoes', 'Sweatshirts', 'T-Shirts', 'Trousers']

Product_Name:
['A-Line Dress', 'Backpack', 'Baggy Jeans', 'Ballet Flats', 'Basic Crew Neck Tee', 'Block Heels', 'Bomber Jacket', 'Cap', 'Cargo Trousers', 'Casual Dress', 'Casual Shirt', 'Casual Sneakers', 'Chinos', 'Crewneck Sweatshirt', 'Crop T-Shirt', 'Denim Jacket', 'Flannel Shirt', 'Floral Midi Dress', 'Formal Shirt', 'Formal Shoes', 'Formal Trousers', 'Graphic Tee', 'Henley T-Shirt', 'High-Rise Skinny Jeans', 'Hoodie', 'Jogger Pants', 'Leather Belt', 'Leather Biker Jacket', 'Linen Shirt', 'Loafers', 'Maxi Dress', 'Mom Fit Jeans', 'Oversized Sweatshirt', 'Oversized T-Shirt', 'Oxford Shirt', 'Palazzo Pants', 'Party Wear Dress', 'Polo T-Shirt', 'Printed Resort Shirt', 'Puffer Jacket', 'Running Shoes', 'Sandals', 'Scarf', 'Slim Fit Jeans', 'Sling Bag', 'Socks Pack', 'Straight Fit Jeans', 'Sunglasses', 'Tote Bag', 'Wallet', 'Windcheater', 'Zip-up Hoodie']

Brand:
['FashionNest', 'ModeStreet', 'StreetMode', 'StyleCraft', 'ThreadLab', 'TrendAura', 'UrbanEdge', 'UrbanThread', 'VogueLine', 'WearWorks']

Size:
['26', '28', '30', '32', '34', '36', '38', '40', 'Free Size', 'L', 'M', 'S', 'UK 10', 'UK 11', 'UK 3', 'UK 4', 'UK 5', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'XL', 'XS', 'XXL']

Color:
['Assorted', 'Beige', 'Black', 'Blue', 'Brown', 'Dark Blue', 'Grey', 'Lavender', 'Light Blue', 'Maroon', 'Mustard', 'Navy Blue', 'Olive Green', 'Pink', 'Red', 'Silver', 'Sky Blue', 'Tan', 'Tortoise Brown', 'Washed Blue', 'White']

State:
['Delhi', 'Gujarat', 'Karnataka', 'Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'West Bengal']

Region:
['Central', 'East', 'North', 'South', 'West']

Return_Status:
['Not Returned', 'Returned']

In [186]:
# 1. Check whether Product_Category matches Size
print("Product category vs size:")

print(
    df.groupby('Product_Category')['Size']
      .unique()
)

# 2. Check whether Age_Group matches Age

conditions = [
    df['Age'].between(18, 24),
    df['Age'].between(25, 34),
    df['Age'].between(35, 44),
    df['Age'].between(45, 55)
]

expected_age_groups = ['18-24', '25-34', '35-44', '45-55']

df['Expected_Age_Group'] = np.select(
    conditions,
    expected_age_groups,
    default='Invalid'
)

print(
    "Age group mismatches:",
    (df['Age_Group'] != df['Expected_Age_Group']).sum()
)

df.drop(columns='Expected_Age_Group', inplace=True)

Product category vs size:
Product_Category
Accessories                  [Free Size, 32, 36, 34, 40, 30, 38]
Dresses                                   [L, M, S, XS, XL, XXL]
Jackets                                   [L, S, M, XS, XL, XXL]
Jeans                               [34, 30, 36, 28, 32, 38, 26]
Shirts                                    [XS, M, S, XXL, XL, L]
Shoes          [UK 6, UK 7, UK 11, UK 8, UK 4, UK 5, UK 9, UK...
Sweatshirts                               [XS, M, L, S, XL, XXL]
T-Shirts                                  [S, L, M, XL, XS, XXL]
Trousers       [S, L, 32, 34, 28, 30, M, XS, 38, 36, XL, 26, ...
Name: Size, dtype: object
Age group mismatches: 0

In [188]:
df.to_csv('Fashion_Retail_Sales_Cleaned_Final.csv', index = False )