In [5]:
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
df = pd.read_csv('Fashion_Retail_Sales_Raw.csv')

In [7]:
df.head()

,Order_ID,Order_Date,Order_Channel,Payment_Method,Customer_ID,Customer_Name,Gender,Age,Age_Group,Customer_Type,...,Unit_Price,Discount_%,Sales_Amount,Cost_Amount,Profit,Profit_Margin_%,City,State,Region,Return_Status
0,ORD-2025-00001,2025-01-01,Website,UPI,CUST-0001,Nisha Kaur,Female,38,35-44,Repeat Customer,...,1099.0,0.0,1099.00,595.08,503.92,45.85,Bengaluru,Karnataka,South,Not Returned
1,ORD-2025-00002,2025-01-01,Website,UPI,CUST-0002,Aarav Krishnan,Male,20,18-24,One-time Customer,...,1599.0,35.0,1039.35,859.71,179.64,17.28,Bengaluru,Karnataka,South,Not Returned
2,ORD-2025-00003,2025/01/01,Mobile App,Cash on Delivery,CUST-0003,Pooja Arora,Female,18,18-24,Repeat Customer,...,449.0,NaN,1257.20,930.12,327.08,26.02,Bengaluru,Karnataka,South,Not Returned
3,ORD-2025-00004,2025-01-01,Physical Store,Credit Card,CUST-0004,Vaishnavi Ghosh,Female,27,25-34,One-time Customer,...,449.0,5.0,1279.65,603.18,676.47,52.86,Kolkata,West Bengal,East,Not Returned
4,ORD-2025-00005,02-01-2025,Physical Store,UPI,CUST-0005,Bhavna Mishra,Female,28,25-34,Repeat Customer,...,1199.0,20.0,1918.40,1195.50,722.90,37.68,Delhi,Delhi,North,Not Returned

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Channel', 'Payment_Method',
       'Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Age_Group',
       'Customer_Type', 'Segment', 'Product_Category', 'Product_Name', 'Brand',
       'Size', 'Color', 'Units_Sold', 'Unit_Price', 'Discount_%',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Profit_Margin_%', 'City',
       'State', 'Region', 'Return_Status'],
      dtype='object')

In [9]:
df.shape

(4015, 27)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4015 entries, 0 to 4014
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          4015 non-null   object
 1   Order_Date        3915 non-null   object
 2   Order_Channel     4015 non-null   object
 3   Payment_Method    4015 non-null   object
 4   Customer_ID       4015 non-null   object
 5   Customer_Name     4015 non-null   object
 6   Gender            4015 non-null   object
 7   Age               4015 non-null   int64
 8   Age_Group         4015 non-null   object
 9   Customer_Type     4015 non-null   object
 10  Segment           3755 non-null   object
 11  Product_Category  4015 non-null   object
 12  Product_Name      4015 non-null   object
 13  Brand             4015 non-null   object
 14  Size              4015 non-null   object
 15  Color             4015 non-null   object
 16  Units_Sold        3764 non-null   float64
 17  Unit_Price        3767 non-null   float64
 18  Discount_%        3666 non-null   float64
 19  Sales_Amount      4015 non-null   float64
 20  Cost_Amount       4015 non-null   float64
 21  Profit            4015 non-null   float64
 22  Profit_Margin_%   3754 non-null   float64
 23  City              4015 non-null   object
 24  State             4015 non-null   object
 25  Region            4015 non-null   object
 26  Return_Status     4015 non-null   object
dtypes: float64(7), int64(1), object(19)
memory usage: 847.0+ KB

In [19]:
df.isnull().sum()

Order_ID              0
Order_Date          100
Order_Channel         0
Payment_Method        0
Customer_ID           0
Customer_Name         0
Gender                0
Age                   0
Age_Group             0
Customer_Type         0
Segment             260
Product_Category      0
Product_Name          0
Brand                 0
Size                  0
Color                 0
Units_Sold          251
Unit_Price          248
Discount_%          349
Sales_Amount          0
Cost_Amount           0
Profit                0
Profit_Margin_%     261
City                  0
State                 0
Region                0
Return_Status         0
dtype: int64

In [21]:
df.isna().sum().sum()

1469

In [95]:
df['Order_Channel'].unique()

array(['Website', 'Mobile App', 'Physical Store'], dtype=object)

In [97]:
df['Payment_Method'].unique()

array(['UPI', 'Cash on Delivery', 'Credit Card', 'Debit Card',
       'Net Banking'], dtype=object)

In [99]:
df['Gender'].value_counts()

Gender
Male      2202
Female    1768
Other       45
Name: count, dtype: int64

In [101]:
df['Age'].nunique()

38

In [103]:
df['Age_Group'].unique()

array(['35-44', '18-24', '25-34', '45-55'], dtype=object)

In [105]:
df['Segment'].unique()

array(['B2C', nan, 'B2B'], dtype=object)

In [107]:
df['Product_Category'].unique()

array(['Trousers', 'Sweatshirts', 'T-Shirts', 'Accessories', 'Shoes',
       'Jeans', 'Jackets', 'Dresses', 'Shirts'], dtype=object)

In [109]:
print(df['Product_Name'].unique())
print('\n')
print("Unique Product Names :",df['Product_Name'].nunique())

['Jogger Pants' 'Crewneck Sweatshirt' 'Basic Crew Neck Tee' 'Scarf'
 'Sling Bag' 'Cap' 'Sandals' 'Hoodie' 'Formal Shoes'
 'Oversized Sweatshirt' 'Loafers' 'Slim Fit Jeans' 'Leather Belt'
 'High-Rise Skinny Jeans' 'Socks Pack' 'Windcheater' 'Party Wear Dress'
 'Oversized T-Shirt' 'Casual Sneakers' 'Zip-up Hoodie' 'Casual Shirt'
 'Backpack' 'Running Shoes' 'Baggy Jeans' 'Polo T-Shirt' 'Puffer Jacket'
 'Graphic Tee' 'Chinos' 'Bomber Jacket' 'Formal Shirt' 'Maxi Dress'
 'Oxford Shirt' 'Linen Shirt' 'Straight Fit Jeans' 'Cargo Trousers'
 'Palazzo Pants' 'Sunglasses' 'Denim Jacket' 'Printed Resort Shirt'
 'A-Line Dress' 'Block Heels' 'Mom Fit Jeans' 'Wallet' 'Flannel Shirt'
 'Floral Midi Dress' 'Henley T-Shirt' 'Casual Dress' 'Formal Trousers'
 'Crop T-Shirt' 'Ballet Flats' 'Leather Biker Jacket' 'Tote Bag']


Unique Product Names : 52

In [111]:
df['Brand'].unique()

array(['ModeStreet', 'TrendAura', 'StreetMode', 'UrbanThread',
       'StyleCraft', 'UrbanEdge', 'FashionNest', 'ThreadLab', 'VogueLine',
       'WearWorks'], dtype=object)

In [113]:
df[df['Units_Sold'] <= 0]

# 15 values are 0 and less than 0.
# total null would be 266 if we convert those 14 values

,Order_ID,Order_Date,Order_Channel,Payment_Method,Customer_ID,Customer_Name,Gender,Age,Age_Group,Customer_Type,...,Unit_Price,Discount_%,Sales_Amount,Cost_Amount,Profit,Profit_Margin_%,City,State,Region,Return_Status
107,ORD-2025-00108,2025-01-11,Mobile App,UPI,CUST-0106,Vihaan Sen,Male,37,35-44,Repeat Customer,...,1699.0,20.0,1359.20,983.57,375.63,27.64,Kolkata,West Bengal,East,Not Returned
132,ORD-2025-00133,14/01/2025,Website,UPI,CUST-0130,Pranav Pawar,Male,22,18-24,One-time Customer,...,1499.0,20.0,1199.20,1093.08,106.12,8.85,Pune,Maharashtra,West,Returned
542,ORD-2025-00541,25-02-2025,Mobile App,UPI,CUST-0434,Ishita Patil,Female,21,18-24,Repeat Customer,...,2499.0,0.0,2499.00,1469.26,1029.74,41.21,Mumbai,Maharashtra,West,Not Returned
545,ORD-2025-00544,2025-02-25,Mobile App,UPI,CUST-0437,Simran Gowda,Female,28,25-34,Repeat Customer,...,1699.0,15.0,2888.30,2021.40,866.90,30.01,Chennai,Tamil Nadu,South,Not Returned
1091,ORD-2025-01088,23-04-2025,Website,Net Banking,CUST-0706,Meera Rao,Female,31,25-34,Repeat Customer,...,599.0,35.0,1168.05,919.74,248.31,21.26,bengaluru,Karnataka,South,Not Returned
1182,ORD-2025-01179,2025-05-04,Website,UPI,CUST-0108,Trisha Mehta,Female,28,25-34,Repeat Customer,...,1299.0,30.0,909.30,770.10,139.20,15.31,Mumbai,Maharashtra,West,Not Returned
1579,ORD-2025-01574,2025-06-14,Physical Store,Credit Card,CUST-0288,Nikhil Pandey,Male,19,18-24,Repeat Customer,...,1999.0,0.0,5997.00,3409.32,2587.68,NaN,Indore,Madhya Pradesh,Central,Not Returned
1622,ORD-2025-01616,2025-06-17,Mobile App,UPI,CUST-0916,Nandini Singh,Female,19,18-24,Repeat Customer,...,1499.0,10.0,2698.20,1838.48,859.72,31.86,Delhi,Delhi,North,Not Returned
1708,ORD-2025-01702,2025/06/25,Physical Store,UPI,CUST-0092,Siddharth Bhosale,Male,28,25-34,Repeat Customer,...,2099.0,30.0,33793.90,24592.98,9200.92,27.23,Pune,Maharashtra,West,Not Returned
2081,ORD-2025-02074,2025-07-29,Mobile App,Credit Card,CUST-0618,Ritesh Singh,Male,27,25-34,Repeat Customer,...,499.0,5.0,948.10,510.48,437.62,46.16,Delhi,Delhi,North,Not Returned
2603,ORD-2025-02593,2025-09-19,Physical Store,UPI,CUST-0150,Aarav Gupta,Male,18,18-24,Repeat Customer,...,3199.0,20.0,5118.40,3699.02,1419.38,27.73,Delhi,Delhi,North,Not Returned
2790,ORD-2025-02780,07/10/2025,Website,UPI,CUST-0452,Lakshmi Kumar,Female,40,35-44,Repeat Customer,...,2999.0,0.0,2999.00,1801.72,1197.28,39.92,Delhi,Delhi,North,Not Returned
3559,ORD-2025-03546,2025-11-28,Physical Store,Debit Card,CUST-0354,Meera Gupta,Female,52,45-55,Repeat Customer,...,1199.0,20.0,14388.00,9819.60,4568.40,31.75,Delhi,Delhi,North,Not Returned
3639,ORD-2025-03626,2025-12-02,Website,UPI,CUST-0295,Vihaan Pillai,Male,19,18-24,Repeat Customer,...,1899.0,35.0,1234.35,995.45,238.90,19.35,Hyderabad,Telangana,South,Not Returned
3967,ORD-2025-03953,2025-12-28,Physical Store,UPI,CUST-0449,Vivek Mishra,Male,53,45-55,Repeat Customer,...,1299.0,25.0,26304.75,19452.42,6852.33,26.05,Delhi,Delhi,North,Not Returned

In [115]:
df[df['Unit_Price'] <= 0]

Empty DataFrame
Columns: [Order_ID, Order_Date, Order_Channel, Payment_Method, Customer_ID, Customer_Name, Gender, Age, Age_Group, Customer_Type, Segment, Product_Category, Product_Name, Brand, Size, Color, Units_Sold, Unit_Price, Discount_%, Sales_Amount, Cost_Amount, Profit, Profit_Margin_%, City, State, Region, Return_Status]
Index: []

[0 rows x 27 columns]

In [117]:
df[df['Discount_%'] < 0]
# 4 negative + 359 null discount percents

,Order_ID,Order_Date,Order_Channel,Payment_Method,Customer_ID,Customer_Name,Gender,Age,Age_Group,Customer_Type,...,Unit_Price,Discount_%,Sales_Amount,Cost_Amount,Profit,Profit_Margin_%,City,State,Region,Return_Status
579,ORD-2025-00578,2025/03/01,Website,Credit Card,CUST-0459,Bhavna Shah,Female,18,18-24,Repeat Customer,...,799.0,-10.0,1438.20,838.94,599.26,41.67,Mumbai,Maharashtra,West,Not Returned
1332,ORD-2025-01328,2025-05-21,Website,Debit Card,CUST-0248,Priya Shinde,Female,44,35-44,Repeat Customer,...,599.0,-5.0,2875.20,1768.80,1106.40,38.48,Ahmedabad,Gujarat,West,Not Returned
1364,ORD-2025-01360,2025-05-25,Mobile App,UPI,CUST-0514,Prashant Rao,Male,25,25-34,Repeat Customer,...,1399.0,-15.0,1399.00,887.71,511.29,36.55,Chennai,Tamil Nadu,South,Not Returned
2717,ORD-2025-02707,2025-10-02,Mobile App,UPI,CUST-1165,Kavya Kumar,Female,26,25-34,Repeat Customer,...,2199.0,-20.0,1869.15,1472.34,396.81,NaN,Mumbai,Maharashtra,West,Not Returned

In [119]:
print('Sales Amount is 0 =',df[df['Sales_Amount'] == 0].shape[0])
print('Sales Amount negative =',df[df['Sales_Amount'] < 0].shape[0])
# total 8 in consistent values

Sales Amount is 0 = 4
Sales Amount negative = 4

In [121]:
print('Cost_Amount is 0 =',df[df['Cost_Amount'] == 0].shape[0])
print('Cost_Amount negative =',df[df['Cost_Amount'] < 0].shape[0])
print(df['Cost_Amount'].isna().sum())

Cost_Amount is 0 = 0
Cost_Amount negative = 0
0

In [123]:
df[df['Discount_%']>100]

,Order_ID,Order_Date,Order_Channel,Payment_Method,Customer_ID,Customer_Name,Gender,Age,Age_Group,Customer_Type,...,Unit_Price,Discount_%,Sales_Amount,Cost_Amount,Profit,Profit_Margin_%,City,State,Region,Return_Status
313,ORD-2025-00312,2025-01-29,Website,Net Banking,CUST-0282,Nandini Varma,Female,28,25-34,Repeat Customer,...,599.0,150.0,8086.5,5852.70,2233.80,27.62,Hyderabad,Telangana,South,Returned
447,ORD-2025-00446,2025-02-14,Mobile App,Net Banking,CUST-0370,Suresh Kaur,Male,32,25-34,Repeat Customer,...,2099.0,110.0,2099.0,1003.55,1095.45,52.19,Delhi,Delhi,North,Not Returned
1146,ORD-2025-01143,2025-04-30,Physical Store,UPI,CUST-0733,Abhishek Verma,Male,34,25-34,Repeat Customer,...,799.0,120.0,1518.1,821.40,696.70,45.89,Delhi,Delhi,North,Not Returned
1320,ORD-2025-01316,2025-05-19,Physical Store,Debit Card,CUST-0807,Ritika Shah,Female,48,45-55,Repeat Customer,...,2499.0,250.0,1749.3,1575.17,174.13,9.95,Pune,Maharashtra,West,Not Returned
1768,ORD-2025-01762,2025/07/01,Mobile App,Credit Card,CUST-0973,Deepak Shinde,Male,29,25-34,Repeat Customer,...,599.0,200.0,1018.3,579.88,438.42,43.05,Mumbai,Maharashtra,West,Not Returned

In [125]:
print(f'''Unique values in City = {df['City'].unique()}

Unique values in state = {df['State'].unique()}

Unique values in Region = {df['Region'].unique()}

Unique values in Return_Status = {df['Return_Status'].unique()}''')

Unique values in City = ['Bengaluru ' 'Bengaluru' 'Kolkata' 'Delhi' 'Pune' 'Mumbai' 'Jaipur'
 'Hyderabad' 'New Delhi' 'Ahmedabad' 'Surat' 'Lucknow' 'Chennai'
 'hyderabad' 'bengaluru' 'delhi' 'Hyd' 'hyderbad' 'Indore' 'kolkata'
 'ahmedabad' 'Ahmadabad' 'Bangalore' 'indore' 'mumbai' 'pune' 'Bombay'
 'MUMBAI' 'PUNE' ' Pune' 'surat' 'chennai' 'jaipur' 'Madras' 'Calcutta'
 'lucknow']

Unique values in state = ['Karnataka' 'West Bengal' 'Delhi' 'Maharashtra' 'Rajasthan' 'Telangana'
 'Gujarat' 'Uttar Pradesh' 'Tamil Nadu' 'Madhya Pradesh']

Unique values in Region = ['South' 'East' 'North' 'West' 'Central']

Unique values in Return_Status = ['Not Returned' 'Returned']

In [127]:
df.duplicated().sum()

15

## Data Cleaning

#### Handelling Order Date

In [131]:
from datetime import datetime

In [133]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format = "mixed",
                                  dayfirst=True)

In [135]:
df['Order_Date']

0      2025-01-01
1      2025-01-01
2      2025-01-01
3      2025-01-01
4      2025-01-02
          ...
4010   2025-12-31
4011   2025-12-31
4012   2025-12-31
4013   2025-12-31
4014   2025-12-31
Name: Order_Date, Length: 4015, dtype: datetime64[ns]

In [137]:
df['Order_Year'] = df['Order_Date'].dt.year.astype('Int64')

In [139]:
df['Order_Month'] = df['Order_Date'].dt.month_name()

In [141]:
df['Order_Quarter'] = 'Q' + df['Order_Date'].dt.quarter.astype('string')

In [143]:
df["Order_Quarter"] = "Q" + df["Order_Date"].dt.quarter.fillna(0).astype(int).astype(str)

In [145]:
df['Order_Quarter']

0       Q1
1       Q1
2       Q1
3       Q1
4       Q1
        ..
4010    Q4
4011    Q4
4012    Q4
4013    Q4
4014    Q4
Name: Order_Quarter, Length: 4015, dtype: object

In [147]:
df.shape

(4015, 30)

#### Handelling Units_Sold

In [150]:
df['Units_Sold'] = df['Units_Sold'].where(df['Units_Sold'] > 0 , np.nan)

In [152]:
df['Units_Sold'].isna().sum()

266

In [154]:
unit_median = df['Units_Sold'].median()

In [156]:
df['Units_Sold'] = df['Units_Sold'].fillna(unit_median)

In [158]:
df['Units_Sold'].isna().sum()

0

#### Handelling Unit_Price

In [161]:
df['Unit_Price'].isna().sum()

248

In [163]:
median_price = df.groupby('Product_Name')['Unit_Price'].transform('median')

In [165]:
df['Unit_Price'] = df['Unit_Price'].fillna(median_price)

In [167]:
df['Unit_Price'].isna().sum()

0

#### Handelling Discount_% and Sales Amount

In [170]:
df['Discount_%'].isna().sum()

349

In [172]:
df['Discount_%'] = df['Discount_%'].where(df['Discount_%'].between(0,100), np.nan)

In [174]:
df['Discount_%'].isna().sum()

358

In [176]:
df.loc[df["Sales_Amount"] <= 0, "Sales_Amount"]

969        0.00
1110   -1599.00
2323       0.00
2324   -1349.25
2798   -1079.60
2812       0.00
3847       0.00
3970   -1438.80
Name: Sales_Amount, dtype: float64

In [178]:
df.loc[df["Sales_Amount"] <= 0, ["Sales_Amount", "Discount_%"]]

      Sales_Amount  Discount_%
969           0.00        10.0
1110      -1599.00         0.0
2323          0.00        20.0
2324      -1349.25        25.0
2798      -1079.60        20.0
2812          0.00        10.0
3847          0.00        10.0
3970      -1438.80        40.0

In [180]:
df.loc[df["Sales_Amount"] <= 0, "Sales_Amount"] = np.nan

In [182]:
df['Sales_Amount'] = df['Sales_Amount'].fillna(df["Units_Sold"] * df["Unit_Price"] * (1 - df["Discount_%"] / 100))

In [184]:
df.loc[[969, 1110, 2323, 2324, 2798, 2812, 3847, 3970],["Units_Sold", "Unit_Price", "Discount_%", "Sales_Amount"]]

      Units_Sold  Unit_Price  Discount_%  Sales_Amount
969          1.0      3099.0        10.0       2789.10
1110         1.0      1599.0         0.0       1599.00
2323         3.0       699.0        20.0       1677.60
2324         1.0      1799.0        25.0       1349.25
2798         1.0      2699.0        20.0       2159.20
2812         1.0      2999.0        10.0       2699.10
3847         1.0      2599.0        10.0       2339.10
3970         2.0      1199.0        40.0       1438.80

In [186]:
df["Discount_%"] = df["Discount_%"].fillna(
    (1 - df["Sales_Amount"] / (df["Units_Sold"] * df["Unit_Price"])) * 100
)

In [188]:
df['Discount_%'].isna().sum()

0

In [190]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Channel', 'Payment_Method',
       'Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Age_Group',
       'Customer_Type', 'Segment', 'Product_Category', 'Product_Name', 'Brand',
       'Size', 'Color', 'Units_Sold', 'Unit_Price', 'Discount_%',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Profit_Margin_%', 'City',
       'State', 'Region', 'Return_Status', 'Order_Year', 'Order_Month',
       'Order_Quarter'],
      dtype='object')

#### Handelling Profit

In [193]:
df['Profit_Renew'] = df['Sales_Amount'] - df['Cost_Amount']

In [195]:
df = df.drop(columns = ['Profit'])

In [197]:
df = df.rename(columns = {'Profit_Renew' : 'Profit'})

In [199]:
df['Profit']

0       503.92
1       179.64
2       327.08
3       676.47
4       722.90
         ...
4010    868.50
4011     29.28
4012     81.40
4013    209.83
4014    486.50
Name: Profit, Length: 4015, dtype: float64

#### Handelling Profit Margin

In [202]:
df['Profit_Margin_Renew'] = (df['Profit'] / df['Sales_Amount']) * 100

In [204]:
df['Profit_Margin_Renew'] = df['Profit_Margin_Renew'].round(2)

In [206]:
df[['Profit_Margin_%' , 'Profit_Margin_Renew']]

      Profit_Margin_%  Profit_Margin_Renew
0               45.85                45.85
1               17.28                17.28
2               26.02                26.02
3               52.86                52.86
4               37.68                37.68
...               ...                  ...
4010            41.42                41.42
4011             9.78                 9.78
4012            34.03                34.03
4013            20.00                20.00
4014              NaN                21.73

[4015 rows x 2 columns]

In [208]:
df = df.drop(columns = ['Profit_Margin_%'])

In [210]:
df = df.rename(columns = {'Profit_Margin_Renew' : 'Profit_Margin_%'})

In [212]:
df['Profit_Margin_%'].isna().sum()

0

#### Handelling Segment

In [215]:
df['Segment'].isna().sum()

260

In [217]:
df['Segment'] = df['Segment'].fillna('Unknown')

In [219]:
df['Segment'].unique()

array(['B2C', 'Unknown', 'B2B'], dtype=object)

In [221]:
df['Segment'].isna().sum()

0

In [223]:
df['City'] = df['City'].str.title()

In [225]:
df['City'] = df['City'].str.strip()

In [227]:
df['City'].unique()

# bangalore
# Hyderabad
# Ahmedabad
# Kolkata
# Mumbai

array(['Bengaluru', 'Kolkata', 'Delhi', 'Pune', 'Mumbai', 'Jaipur',
       'Hyderabad', 'New Delhi', 'Ahmedabad', 'Surat', 'Lucknow',
       'Chennai', 'Hyd', 'Hyderbad', 'Indore', 'Ahmadabad', 'Bangalore',
       'Bombay', 'Madras', 'Calcutta'], dtype=object)

In [229]:
df['City'] = df['City'].replace({
    'Bengaluru' : 'Bangalore',
    'Calcutta'  : 'Kolkata',
    'Bombay' : 'Mumbai',
    'Hyderbad' : 'Hyderabad',
    'Hyd' : 'Hyderabad',
    'Ahmadabad' : 'Ahmedabad'})

In [231]:
df['City'].unique()

array(['Bangalore', 'Kolkata', 'Delhi', 'Pune', 'Mumbai', 'Jaipur',
       'Hyderabad', 'New Delhi', 'Ahmedabad', 'Surat', 'Lucknow',
       'Chennai', 'Indore', 'Madras'], dtype=object)

In [233]:
df.isna().sum()

Order_ID              0
Order_Date          100
Order_Channel         0
Payment_Method        0
Customer_ID           0
Customer_Name         0
Gender                0
Age                   0
Age_Group             0
Customer_Type         0
Segment               0
Product_Category      0
Product_Name          0
Brand                 0
Size                  0
Color                 0
Units_Sold            0
Unit_Price            0
Discount_%            0
Sales_Amount          0
Cost_Amount           0
City                  0
State                 0
Region                0
Return_Status         0
Order_Year          100
Order_Month         100
Order_Quarter         0
Profit                0
Profit_Margin_%       0
dtype: int64

In [240]:
median_date = df['Order_Date'].median()
median_date

Timestamp('2025-07-22 00:00:00')

In [242]:
df['Order_Date'] = df['Order_Date'].fillna(median_date)

In [244]:
df['Order_Date'].isna().sum()

0

In [250]:
year = df['Order_Date'].dt.year
month = df['Order_Date'].dt.month_name()

In [276]:
df = df.drop(columns = ['Order_Month'])

In [280]:
df['Order_Month'] = df['Order_Date'].dt.month_name()

In [282]:
df['Order_Month']

0        January
1        January
2        January
3        January
4        January
          ...
4010    December
4011    December
4012    December
4013    December
4014    December
Name: Order_Month, Length: 4015, dtype: object

In [284]:
df.isna().sum()

Order_ID            0
Order_Date          0
Order_Channel       0
Payment_Method      0
Customer_ID         0
Customer_Name       0
Gender              0
Age                 0
Age_Group           0
Customer_Type       0
Segment             0
Product_Category    0
Product_Name        0
Brand               0
Size                0
Color               0
Units_Sold          0
Unit_Price          0
Discount_%          0
Sales_Amount        0
Cost_Amount         0
City                0
State               0
Region              0
Return_Status       0
Order_Year          0
Order_Quarter       0
Profit              0
Profit_Margin_%     0
Order_Month         0
dtype: int64

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4015 entries, 0 to 4014
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          4015 non-null   object
 1   Order_Date        4015 non-null   datetime64[ns]
 2   Order_Channel     4015 non-null   object
 3   Payment_Method    4015 non-null   object
 4   Customer_ID       4015 non-null   object
 5   Customer_Name     4015 non-null   object
 6   Gender            4015 non-null   object
 7   Age               4015 non-null   int64
 8   Age_Group         4015 non-null   object
 9   Customer_Type     4015 non-null   object
 10  Segment           4015 non-null   object
 11  Product_Category  4015 non-null   object
 12  Product_Name      4015 non-null   object
 13  Brand             4015 non-null   object
 14  Size              4015 non-null   object
 15  Color             4015 non-null   object
 16  Units_Sold        4015 non-null   float64
 17  Unit_Price        4015 non-null   float64
 18  Discount_%        4015 non-null   float64
 19  Sales_Amount      4015 non-null   float64
 20  Cost_Amount       4015 non-null   float64
 21  City              4015 non-null   object
 22  State             4015 non-null   object
 23  Region            4015 non-null   object
 24  Return_Status     4015 non-null   object
 25  Order_Year        4015 non-null   Int64
 26  Order_Quarter     4015 non-null   object
 27  Profit            4015 non-null   float64
 28  Profit_Margin_%   4015 non-null   float64
 29  Order_Month       4015 non-null   object
dtypes: Int64(1), datetime64[ns](1), float64(7), int64(1), object(20)
memory usage: 945.1+ KB

In [289]:
df.to_csv('Fashion_Retail_Sales_Cleaned.csv')

In [295]:
df = df.drop_duplicates('Order_ID')

In [299]:
df.duplicated().sum()

0

In [301]:
df['City'].unique()

array(['Bangalore', 'Kolkata', 'Delhi', 'Pune', 'Mumbai', 'Jaipur',
       'Hyderabad', 'New Delhi', 'Ahmedabad', 'Surat', 'Lucknow',
       'Chennai', 'Indore', 'Madras'], dtype=object)

In [305]:
df['City'] = df['City'].replace({
    'Banagalore' : 'Bengaluru',
    'New Delhi' : 'Delhi',
    'Madras' : 'Chennai'})

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13612\34746476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].replace({

In [307]:
print(df['City'].value_counts())
# print(df.groupby(['City', 'State', 'Region']).size())

City
Mumbai       699
Bangalore    622
Delhi        538
Pune         493
Hyderabad    393
Chennai      339
Kolkata      280
Ahmedabad    198
Surat        129
Jaipur       125
Indore       113
Lucknow       71
Name: count, dtype: int64